apiVersion: rbac.authorization.k8s.io/v1
kind: Rol
metadata:
  namespace: roboshop
  name: roboshop-trainee
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]